export const ActionTypes = {
    SET_TEMPLATES: 'SET_TEMPLATES',
    ALL_TEMPLATES: 'ALL_TEMPLATES',
    SORTED_TEMPLATES_CATEGORY: 'SORTED_TEMPLATES_CATEGORY',
    SORTED_TEMPLATES_ORDER: 'SORTED_TEMPLATES_ORDER',
    SORTED_TEMPLATES_DATES: 'SORTED_TEMPLATES_DATES'
}